# Generated by Django 4.1.5 on 2023-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catry',
            field=models.CharField(choices=[('Sarees', 'Sarees'), ('Dresses', 'Dresses'), ('Baby Costumes', 'Baby Costumes'), ('Girls Costumes', 'Girls Costumes')], default=('Sarees', 'Sarees'), max_length=20),
        ),
    ]
